services:
    _defaults:
        autoconfigure: true
        autowire: true

    Torr\Rad\:
        resource: ../src/*
        exclude: ../src/{Entity,Exception,Pagination/Paginat*,TorrRadBundle.php}
