services:
    _defaults:
        autoconfigure: true
        autowire: true

    Torr\Rad\:
        resource: ../src/*
        exclude:
            - ../src/Api
            - ../src/Entity
            - ../src/Exception
            - ../src/Pagination/Paginat*
            - ../src/Route
            - ../src/TorrRadBundle.php
